import { Employee, SpecialEvent, WFHRequest, PayrollRecord, CalendarEntry, CurrentUser } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'EMP-001',
    firstName: 'Priya',
    lastName: 'Nair',
    email: 'priya.nair@acmecorp.com',
    phone: '+1 (555) 234-5678',
    avatarColor: '#E65100',
    department: 'Engineering',
    jobTitle: 'Senior Software Engineer',
    employmentType: 'Full-time',
    joiningDate: '12 Mar 2021',
    joiningDateIso: '2021-03-12',
    manager: 'Marcus Webb',
    location: 'San Francisco, CA',
    status: 'Active',
    salary: 135000,
    bankName: 'Silicon Valley Bank',
    accountNumber: '•••• •••• 4421',
    emergencyContact: 'Rohan Nair (Spouse)',
    emergencyPhone: '+1 (555) 234-9988',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=256&auto=format&fit=crop',
  },
  {
    id: 'emp-2',
    employeeId: 'EMP-002',
    firstName: 'Marcus',
    lastName: 'Webb',
    email: 'marcus.webb@acmecorp.com',
    phone: '+1 (555) 345-6789',
    avatarColor: '#FF6D00',
    department: 'Product',
    jobTitle: 'Product Manager',
    employmentType: 'Full-time',
    joiningDate: '05 Jul 2019',
    joiningDateIso: '2019-07-05',
    manager: 'Elena Rostova (VP Product)',
    location: 'New York, NY',
    status: 'Active',
    salary: 148000,
    bankName: 'Chase Bank',
    accountNumber: '•••• •••• 8832',
    emergencyContact: 'Sarah Webb (Sister)',
    emergencyPhone: '+1 (555) 345-0011',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=256&auto=format&fit=crop',
  },
  {
    id: 'emp-3',
    employeeId: 'EMP-003',
    firstName: 'Leila',
    lastName: 'Ahmadi',
    email: 'leila.ahmadi@acmecorp.com',
    phone: '+1 (555) 456-7890',
    avatarColor: '#FF7900',
    department: 'Design',
    jobTitle: 'UI/UX Lead',
    employmentType: 'Full-time',
    joiningDate: '22 Jan 2020',
    joiningDateIso: '2020-01-22',
    manager: 'Marcus Webb',
    location: 'San Francisco, CA',
    status: 'Active',
    salary: 130000,
    bankName: 'Bank of America',
    accountNumber: '•••• •••• 1290',
    emergencyContact: 'Kian Ahmadi (Brother)',
    emergencyPhone: '+1 (555) 456-2244',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=256&auto=format&fit=crop',
  },
  {
    id: 'emp-4',
    employeeId: 'EMP-004',
    firstName: 'Daniel',
    lastName: 'Osei',
    email: 'daniel.osei@acmecorp.com',
    phone: '+1 (555) 567-8901',
    avatarColor: '#F57C00',
    department: 'Finance',
    jobTitle: 'Financial Analyst',
    employmentType: 'Full-time',
    joiningDate: '18 Sep 2022',
    joiningDateIso: '2022-09-18',
    manager: 'Thomas Wright (CFO)',
    location: 'Chicago, IL',
    status: 'Active',
    salary: 115000,
    bankName: 'Wells Fargo',
    accountNumber: '•••• •••• 7765',
    emergencyContact: 'Abena Osei (Mother)',
    emergencyPhone: '+1 (555) 567-3311',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=256&auto=format&fit=crop',
  },
  {
    id: 'emp-5',
    employeeId: 'EMP-005',
    firstName: 'Sofia',
    lastName: 'Martínez',
    email: 'sofia.martinez@acmecorp.com',
    phone: '+1 (555) 678-9012',
    avatarColor: '#EF6C00',
    department: 'Marketing',
    jobTitle: 'Growth Manager',
    employmentType: 'Full-time',
    joiningDate: '03 Feb 2023',
    joiningDateIso: '2023-02-03',
    manager: 'David Chen (CMO)',
    location: 'Austin, TX',
    status: 'Active',
    salary: 122000,
    bankName: 'Citibank',
    accountNumber: '•••• •••• 6519',
    emergencyContact: 'Carlos Martínez (Father)',
    emergencyPhone: '+1 (555) 678-8822',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=256&auto=format&fit=crop',
  },
  {
    id: 'emp-6',
    employeeId: 'INT-001',
    firstName: 'Ryo',
    lastName: 'Tanaka',
    email: 'ryo.tanaka@acmecorp.com',
    phone: '+1 (555) 789-0123',
    avatarColor: '#FF6D00',
    department: 'Engineering',
    jobTitle: 'Software Engineering Intern',
    employmentType: 'Intern',
    joiningDate: '01 Jun 2026',
    joiningDateIso: '2026-06-01',
    manager: 'Priya Nair',
    location: 'San Francisco, CA',
    status: 'Active',
    salary: 45000,
    bankName: 'Chase Bank',
    accountNumber: '•••• •••• 3341',
    emergencyContact: 'Kenji Tanaka (Brother)',
    emergencyPhone: '+1 (555) 789-5566',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=256&auto=format&fit=crop',
  },
  {
    id: 'emp-7',
    employeeId: 'INT-002',
    firstName: 'Amara',
    lastName: 'Diallo',
    email: 'amara.diallo@acmecorp.com',
    phone: '+1 (555) 890-1234',
    avatarColor: '#FB8C00',
    department: 'Marketing',
    jobTitle: 'Marketing Intern',
    employmentType: 'Intern',
    joiningDate: '01 Jun 2026',
    joiningDateIso: '2026-06-01',
    manager: 'Sofia Martínez',
    location: 'Austin, TX',
    status: 'Active',
    salary: 42000,
    bankName: 'Wells Fargo',
    accountNumber: '•••• •••• 9920',
    emergencyContact: 'Fatou Diallo (Sister)',
    emergencyPhone: '+1 (555) 890-7788',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=256&auto=format&fit=crop',
  },
  {
    id: 'emp-8',
    employeeId: 'INT-003',
    firstName: 'Chloe',
    lastName: 'Park',
    email: 'chloe.park@acmecorp.com',
    phone: '+1 (555) 901-2345',
    avatarColor: '#FF7900',
    department: 'Design',
    jobTitle: 'Design Intern',
    employmentType: 'Intern',
    joiningDate: '15 Jun 2026',
    joiningDateIso: '2026-06-15',
    manager: 'Leila Ahmadi',
    location: 'San Francisco, CA',
    status: 'Active',
    salary: 44000,
    bankName: 'Bank of America',
    accountNumber: '•••• •••• 5512',
    emergencyContact: 'Min-jun Park (Father)',
    emergencyPhone: '+1 (555) 901-1122',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=256&auto=format&fit=crop',
  },
];

export const INITIAL_EVENTS: SpecialEvent[] = [

  {
    id: 'evt-1',
    employeeId: 'emp-2',
    employeeName: 'Marcus Webb',
    title: 'Marcus Webb — Birthday',
    type: 'Birthday',
    date: '2026-08-14',
    description: 'Product Manager birthday celebration at 4:30 PM in the commons.',
  },
  {
    id: 'evt-2',
    employeeId: 'emp-3',
    employeeName: 'Leila Ahmadi',
    title: 'Leila Ahmadi — Work Anniversary (6 yrs)',
    type: 'Work Anniversary',
    date: '2026-08-22',
    years: 6,
    description: 'Celebrating 6 years of outstanding design leadership!',
  },
  {
    id: 'evt-3',
    employeeName: 'All Company',
    title: 'Independence Day (Holiday)',
    type: 'Company Holiday',
    date: '2026-08-15',
    description: 'Federal company-wide holiday. Offices will be closed.',
  },
  {
    id: 'evt-4',
    employeeId: 'emp-1',
    employeeName: 'Priya Nair',
    title: 'Priya Nair — Birthday',
    type: 'Birthday',
    date: '2026-09-02',
    description: 'Senior Software Engineer birthday celebration.',
  },
  {
    id: 'evt-5',
    employeeName: 'All Company',
    title: 'Onam Eve (Holiday)',
    type: 'Company Holiday',
    date: '2026-08-09',
    description: 'Regional corporate cultural holiday observance.',
  },
  {
    id: 'evt-6',
    employeeName: 'All Company',
    title: 'Assumption Day (Holiday)',
    type: 'Company Holiday',
    date: '2026-08-15',
    description: 'Official corporate calendar holiday.',
  },
];

export const INITIAL_WFH_REQUESTS: WFHRequest[] = [
  {
    id: 'wfh-1',
    employeeId: 'emp-5',
    employeeName: 'Sofia Martínez',
    department: 'Marketing',
    requestDate: '2026-08-10',
    startDate: '2026-08-12',
    endDate: '2026-08-13',
    displayDateRange: 'Aug 12–13, 2026',
    reason: 'Deep work sprint on Q3 campaign launch and partner calls.',
    status: 'Pending',
  },
  {
    id: 'wfh-2',
    employeeId: 'emp-6',
    employeeName: 'Ryo Tanaka',
    department: 'Engineering',
    requestDate: '2026-08-11',
    startDate: '2026-08-15',
    endDate: '2026-08-15',
    displayDateRange: 'Aug 15, 2026',
    reason: 'University thesis final evaluation defense prep day.',
    status: 'Pending',
  },
  {
    id: 'wfh-3',
    employeeId: 'emp-8',
    employeeName: 'Chloe Park',
    department: 'Design',
    requestDate: '2026-08-11',
    startDate: '2026-08-19',
    endDate: '2026-08-20',
    displayDateRange: 'Aug 19–20, 2026',
    reason: 'Figma remote design systems conference and workshop.',
    status: 'Pending',
  },
  {
    id: 'wfh-4',
    employeeId: 'emp-1',
    employeeName: 'Priya Nair',
    department: 'Engineering',
    requestDate: '2026-08-08',
    startDate: '2026-08-11',
    endDate: '2026-08-11',
    displayDateRange: 'Aug 11, 2026',
    reason: 'Off-site server infrastructure migration and zero-downtime cutover.',
    status: 'Approved',
    approvedBy: 'HR Admin',
    reviewedAt: '2026-08-09',
  },
  {
    id: 'wfh-5',
    employeeId: 'emp-3',
    employeeName: 'Leila Ahmadi',
    department: 'Design',
    requestDate: '2026-08-09',
    startDate: '2026-08-11',
    endDate: '2026-08-11',
    displayDateRange: 'Aug 11, 2026',
    reason: 'Focusing on 2027 design tokens and component audit.',
    status: 'Approved',
    approvedBy: 'HR Admin',
    reviewedAt: '2026-08-10',
  },
  {
    id: 'wfh-6',
    employeeId: 'emp-2',
    employeeName: 'Marcus Webb',
    department: 'Product',
    requestDate: '2026-08-10',
    startDate: '2026-08-17',
    endDate: '2026-08-18',
    displayDateRange: 'Aug 17–18, 2026',
    reason: 'Strategic planning documentation with executive leadership.',
    status: 'Approved',
    approvedBy: 'HR Admin',
    reviewedAt: '2026-08-10',
  },
];

export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'pay-1',
    employeeId: 'EMP-001',
    employeeName: 'Priya Nair',
    department: 'Engineering',
    jobTitle: 'Senior Software Engineer',
    basicSalary: 8500,
    housingAllowance: 1200,
    transportAllowance: 400,
    otherAllowance: 300,
    grossSalary: 10400,
    deductions: 1200,
    netSalary: 9200,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-2',
    employeeId: 'EMP-002',
    employeeName: 'Marcus Webb',
    department: 'Product',
    jobTitle: 'Product Manager',
    basicSalary: 9200,
    housingAllowance: 1500,
    transportAllowance: 500,
    otherAllowance: 400,
    grossSalary: 11600,
    deductions: 1400,
    netSalary: 10200,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-3',
    employeeId: 'EMP-003',
    employeeName: 'Leila Ahmadi',
    department: 'Design',
    jobTitle: 'UI/UX Lead',
    basicSalary: 8000,
    housingAllowance: 1200,
    transportAllowance: 400,
    otherAllowance: 250,
    grossSalary: 9850,
    deductions: 1150,
    netSalary: 8700,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-4',
    employeeId: 'EMP-004',
    employeeName: 'Daniel Osei',
    department: 'Finance',
    jobTitle: 'Financial Analyst',
    basicSalary: 7200,
    housingAllowance: 1000,
    transportAllowance: 350,
    otherAllowance: 200,
    grossSalary: 8750,
    deductions: 1050,
    netSalary: 7700,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-5',
    employeeId: 'EMP-005',
    employeeName: 'Sofia Martínez',
    department: 'Marketing',
    jobTitle: 'Growth Manager',
    basicSalary: 7600,
    housingAllowance: 1100,
    transportAllowance: 400,
    otherAllowance: 250,
    grossSalary: 9350,
    deductions: 1100,
    netSalary: 8250,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-6',
    employeeId: 'INT-001',
    employeeName: 'Ryo Tanaka',
    department: 'Engineering',
    jobTitle: 'Software Engineering Intern',
    basicSalary: 3000,
    housingAllowance: 400,
    transportAllowance: 200,
    otherAllowance: 100,
    grossSalary: 3700,
    deductions: 350,
    netSalary: 3350,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-7',
    employeeId: 'INT-002',
    employeeName: 'Amara Diallo',
    department: 'Marketing',
    jobTitle: 'Marketing Intern',
    basicSalary: 2800,
    housingAllowance: 400,
    transportAllowance: 200,
    otherAllowance: 100,
    grossSalary: 3500,
    deductions: 300,
    netSalary: 3200,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-8',
    employeeId: 'INT-003',
    employeeName: 'Chloe Park',
    department: 'Design',
    jobTitle: 'Design Intern',
    basicSalary: 2900,
    housingAllowance: 400,
    transportAllowance: 200,
    otherAllowance: 100,
    grossSalary: 3600,
    deductions: 320,
    netSalary: 3280,
    status: 'Paid',
    paymentDate: '2026-08-01',
  },
];

export const INITIAL_CALENDAR_ENTRIES: CalendarEntry[] = [
  { id: 'c-1', employeeName: 'All Company', date: '2026-08-02', type: 'Holiday', title: 'Independence Day' },
  { id: 'c-2', employeeName: 'Daniel Osei', employeeId: 'emp-4', date: '2026-08-03', type: 'WFH' },
  { id: 'c-3', employeeName: 'Daniel Osei', employeeId: 'emp-4', date: '2026-08-04', type: 'Approved WFH' },
  { id: 'c-4', employeeName: 'Ryo Tanaka', employeeId: 'emp-6', date: '2026-08-05', type: 'WFH' },
  { id: 'c-5', employeeName: 'Priya Nair', employeeId: 'emp-1', date: '2026-08-06', type: 'WFH' },
  { id: 'c-6', employeeName: 'Ryo Tanaka', employeeId: 'emp-6', date: '2026-08-06', type: 'WFH' },
  { id: 'c-7', employeeName: 'Priya Nair', employeeId: 'emp-1', date: '2026-08-07', type: 'WFH' },
  { id: 'c-8', employeeName: 'Ryo Tanaka', employeeId: 'emp-6', date: '2026-08-07', type: 'Approved WFH' },
  { id: 'c-9', employeeName: 'All Company', date: '2026-08-09', type: 'Holiday', title: 'Onam Eve' },
  { id: 'c-10', employeeName: 'Leila Ahmadi', employeeId: 'emp-3', date: '2026-08-10', type: 'WFH' },
  { id: 'c-11', employeeName: 'Chloe Park', employeeId: 'emp-8', date: '2026-08-10', type: 'Approved WFH' },
  // August 11, 2026 TODAY
  { id: 'c-12', employeeName: 'Leila Ahmadi', employeeId: 'emp-3', date: '2026-08-11', type: 'Approved WFH' },
  { id: 'c-13', employeeName: 'Sofia Martínez', employeeId: 'emp-5', date: '2026-08-11', type: 'Leave', reason: 'Personal Leave' },
  // August 12-15
  { id: 'c-14', employeeName: 'Sofia Martínez', employeeId: 'emp-5', date: '2026-08-12', type: 'WFH' },
  { id: 'c-15', employeeName: 'Sofia Martínez', employeeId: 'emp-5', date: '2026-08-13', type: 'Leave' },
  { id: 'c-16', employeeName: 'Sofia Martínez', employeeId: 'emp-5', date: '2026-08-14', type: 'Approved WFH' },
  { id: 'c-17', employeeName: 'All Company', date: '2026-08-15', type: 'Holiday', title: 'Assumption Day' },
  // August 17-21
  { id: 'c-18', employeeName: 'Marcus Webb', employeeId: 'emp-2', date: '2026-08-17', type: 'WFH' },
  { id: 'c-19', employeeName: 'Amara Diallo', employeeId: 'emp-7', date: '2026-08-17', type: 'Approved WFH' },
  { id: 'c-20', employeeName: 'Marcus Webb', employeeId: 'emp-2', date: '2026-08-18', type: 'Approved WFH' },
  { id: 'c-21', employeeName: 'Daniel Osei', employeeId: 'emp-4', date: '2026-08-19', type: 'WFH' },
  { id: 'c-22', employeeName: 'Daniel Osei', employeeId: 'emp-4', date: '2026-08-20', type: 'WFH' },
  { id: 'c-23', employeeName: 'Daniel Osei', employeeId: 'emp-4', date: '2026-08-21', type: 'Approved WFH' },
  // August 24-28
  { id: 'c-24', employeeName: 'Priya Nair', employeeId: 'emp-1', date: '2026-08-24', type: 'WFH' },
  { id: 'c-25', employeeName: 'Ryo Tanaka', employeeId: 'emp-6', date: '2026-08-24', type: 'Approved WFH' },
  { id: 'c-26', employeeName: 'Priya Nair', employeeId: 'emp-1', date: '2026-08-25', type: 'WFH' },
  { id: 'c-27', employeeName: 'Chloe Park', employeeId: 'emp-8', date: '2026-08-25', type: 'WFH' },
  { id: 'c-28', employeeName: 'Leila Ahmadi', employeeId: 'emp-3', date: '2026-08-26', type: 'WFH' },
  { id: 'c-29', employeeName: 'Chloe Park', employeeId: 'emp-8', date: '2026-08-26', type: 'WFH' },
  { id: 'c-30', employeeName: 'Leila Ahmadi', employeeId: 'emp-3', date: '2026-08-27', type: 'WFH' },
  { id: 'c-31', employeeName: 'Chloe Park', employeeId: 'emp-8', date: '2026-08-27', type: 'Approved WFH' },
  { id: 'c-32', employeeName: 'Leila Ahmadi', employeeId: 'emp-3', date: '2026-08-28', type: 'Approved WFH' },
  { id: 'c-33', employeeName: 'Sofia Martínez', employeeId: 'emp-5', date: '2026-08-31', type: 'Approved WFH' },
];

export const CURRENT_DATE_REFERENCE = '2026-08-11';
export const CURRENT_USER_ADMIN: CurrentUser = {
  id: 'usr-admin',
  name: 'HR Admin (Eleanor)',
  email: 'hr.admin@acmecorp.com',
  role: 'admin',
  title: 'Human Resources Director',
  department: 'People & Operations',
  phone: '+1 (555) 880-9900',
  location: 'San Francisco, CA',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=256&auto=format&fit=crop',
};
export const CURRENT_USER_EMPLOYEE: CurrentUser = {
  id: 'emp-1',
  name: 'Priya Nair',
  email: 'priya.nair@acmecorp.com',
  role: 'employee',
  employeeId: 'EMP-001',
  department: 'Engineering',
  title: 'Senior Software Engineer',
  phone: '+1 (555) 234-5678',
  location: 'San Francisco, CA',
  avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=256&auto=format&fit=crop',
};

